name: Deploy Next.js Frontend (standalone) to Azure App Service

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & build (Next standalone)
        # nếu repo FE riêng thì bỏ working-directory hoặc để "."
        working-directory: bambooshop-frontend
        run: |
          npm ci
          npm run build

      - name: Package (standalone)
        run: |
          rm -rf deploy
          mkdir -p deploy/.next
          cp -R bambooshop-frontend/.next/standalone/* deploy/
          cp -R bambooshop-frontend/.next/static deploy/.next/static
          cp -R bambooshop-frontend/public deploy/public
          test -f deploy/server.js
          test -f deploy/package.json
          cd deploy && zip -r app.zip .
      - name: Debug secrets presence (safe)
        run: |
          test -n "${{ secrets.AZURE_CLIENT_ID }}" && echo "CLIENT_ID OK" || echo "CLIENT_ID MISSING"
          test -n "${{ secrets.AZURE_TENANT_ID }}" && echo "TENANT_ID OK" || echo "TENANT_ID MISSING"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Wait for SCM
        run: sleep 30

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: deploy/app.zip
