// Product page Tailwind styles
export const productPageStyles = {
  main: 'py-16 px-6 sm:px-8 lg:px-12 relative overflow-hidden bg-gradient-to-br from-[#f0f7f2] via-[#c8e6c9] to-[#a5d6a7] min-h-screen',
  decorativeBlurlg: 'absolute top-20 right-0 w-80 h-80 bg-green-300 rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-pulse',
  decorativeBlurMd: 'absolute bottom-20 left-10 w-96 h-96 bg-emerald-200 rounded-full mix-blend-multiply filter blur-3xl opacity-15 animate-pulse delay-4000',
  decorativeBlurSm: 'absolute top-1/2 right-1/4 w-72 h-72 bg-green-400 rounded-full mix-blend-multiply filter blur-3xl opacity-10',
  container: 'max-w-7xl mx-auto relative z-10',
  headerContainer: 'flex items-center justify-between mb-8',
  titleBlock: 'mt-6',
  title: 'text-3xl font-bold text-[#1a3a2a]',
  subtitle: 'text-sm text-[#264653] mt-2',
  backButton: 'inline-flex items-center gap-2 px-3 py-1.5 border border-emerald-500 text-emerald-500 rounded-md text-sm hover:bg-emerald-50',
  gridContainer: 'grid grid-cols-1 md:grid-cols-4 gap-8 items-start',
  sidebar: 'md:col-span-1 bg-white p-4 rounded-xl shadow-sm border border-emerald-50',
  formGroup: 'mb-3',
  label: 'block text-xs font-medium text-gray-700 mb-1',
  input: 'w-full px-2 py-1 border rounded-md text-sm placeholder-gray-600 text-gray-700 focus:outline-none focus:ring-1 focus:ring-emerald-200',
  select: 'w-full px-2 py-1 border rounded-md text-sm text-gray-800',
  option: 'text-gray-800',
  priceInputs: 'flex gap-2',
  priceInput: 'w-1/2 px-2 py-1 border rounded-md text-sm placeholder-gray-600 text-gray-700',
  resetButton: 'px-3 py-1 text-sm border border-gray-200 rounded-md bg-white text-gray-700 hover:bg-gray-50',
  productSection: 'md:col-span-3',
  loadingContainer: 'text-center py-12',
  loadingText: 'inline-block animate-pulse px-6 py-3 bg-emerald-100 text-emerald-700 rounded-md',
  errorText: 'text-center py-12 text-red-600',
  productGrid: 'grid sm:grid-cols-2 lg:grid-cols-3 gap-8',
  productCard: 'bg-white rounded-2xl shadow-md overflow-hidden border border-emerald-100',
  productImage: 'h-44 w-full bg-gray-100 flex items-center justify-center',
  productImageElement: 'h-full w-full object-cover',
  productPlaceholder: 'text-6xl',
  productContent: 'p-6',
  productName: 'text-xl font-semibold text-[#1a3a2a] mb-2',
  productDescription: 'text-sm text-[#264653] mb-4',
  productFooter: 'flex items-center justify-between',
  productPrice: 'text-2xl font-bold text-[#2d6a4f]',
  productLink: 'px-4 py-2 bg-emerald-500 text-white rounded-md',
};
